#====================================================================
# File automatically generated by ES3  
# This file regenerated each time you run EISC Studio, so save under a 
# new name if you hand edit, or it will be overwritten.
#				www.adc.co.kr
#====================================================================



ECHO	=	echo.exe
CC	=	ae32000-elf-gcc
AS	=	ae32000-elf-as
LD	=	ae32000-elf-ld
AR	=	ae32000-elf-ar
OBJCOPY	=	ae32000-elf-objcopy
OBJDUMP	=	ae32000-elf-objdump
CFLAGS	=	 -g -fno-strength-reduce -Wall 
ASFLAGS	=	 -gstabs 
LDFLAGS	=	-Wall -nostartfiles -lgcc -lc -lm -Wl,--warn-common 
DISFLAGS	=	-dzShxl
ARFLAGS	=	rcusv
#====== Directory =====
OUTPUTDIR	=	output/
OBJDIR	=	obj/
INCDIR	=	\
	 -I"include"
LIBDIR	=	
LIBS	=	\
	lib/libadLuna.a

SOURCES	 += startup/adLunaInit.c
SOURCES	 += startup/BoardInit_T4MK.c
SOURCES	 += startup/startup_adLuna.s
SOURCES	 += main.c
SOURCES	 += Raon_Func.c

OBJECTS	 += ${OBJDIR}adLunaInit.o
OBJECTS	 += ${OBJDIR}BoardInit_T4MK.o
OBJECTS	 += ${OBJDIR}startup_adLuna.o
OBJECTS	 += ${OBJDIR}main.o
OBJECTS	 += ${OBJDIR}Raon_Func.o

DEPS	 += ${OBJDIR}adLunaInit.d
DEPS	 += ${OBJDIR}BoardInit_T4MK.d
DEPS	 += ${OBJDIR}startup_adLuna.d
DEPS	 += ${OBJDIR}main.d
DEPS	 += ${OBJDIR}Raon_Func.d



#====== TAGET Define =====
TARGET	=	$(OUTPUTDIR)Quming_AIR

BINARY	=	$(TARGET).bin

HEX	=	$(TARGET).hex

DISASSEMBLE	=	$(TARGET).dis

ALL	:	$(TARGET) $(BINARY) 

all	:	$(TARGET) $(BINARY) 

binary	:	$(BINARY)

bin	:	$(BINARY)

hex	:	$(HEX)

disassemble	:	$(DISASSEMBLE)

dis	:	$(DISASSEMBLE)

clean	:
	@$(ECHO) 'Deleting intermediate and output files... '
	rm -f $(OBJECTS) $(TARGET) $(DISASSEMBLE) $(BINARY) $(DEPS)
	@$(ECHO) ' '

cleanall	:
	@$(ECHO) 'Deleting intermediate and output files... '
	rm -f $(OBJECTS) $(TARGET) $(DISASSEMBLE) $(BINARY) $(DEPS)
	@$(ECHO) ' '

cleanobj	:
	@$(ECHO) 'Deleting intermediate files... '
	rm -f $(OBJECTS) 
	@$(ECHO) ' '

cleanbin	:
	rm -f $(BINARY)
	@$(ECHO) ' '

cleandis	:
	rm -f $(DISASSEMBLE)
	@$(ECHO) ' '

ifeq ($(FULLMSG),no)
ECHOMARK = @
else
ECHOMARK = 
endif

-include ${OBJDIR}adLunaInit.d
-include ${OBJDIR}BoardInit_T4MK.d
-include ${OBJDIR}startup_adLuna.d
-include ${OBJDIR}main.d
-include ${OBJDIR}Raon_Func.d

#============= TARGET ====================
${TARGET} : Makefile.mk ${OBJECTS} ${LIBS} startup/adLuna.ld
	@$(ECHO) 'Linking...'
	$(ECHOMARK)$(CC) -o $(TARGET) $(OBJECTS) $(LIBDIR) -Xlinker --start-group $(LIBS) -Xlinker --end-group $(LDFLAGS) -Xlinker -T"startup/adLuna.ld"
	@$(ECHO) 'Finished building : $@ '
	@$(ECHO) ' '

$(BINARY): $(TARGET)
	@$(ECHO) 'Generating binary file...'
	$(ECHOMARK)$(OBJCOPY) -O binary $(TARGET) $@
	@$(ECHO) 'Finished building : $@ '
	@$(ECHO) ' '
	@$(ECHO) 'Program section information '
	$(ECHOMARK)size $(TARGET)
	@$(ECHO) ' '

$(DISASSEMBLE) : $(TARGET)
	@$(ECHO) 'Generating disassemble file...'
	$(ECHOMARK)$(OBJDUMP) $(DISFLAGS) $(TARGET) > $@ 
	@$(ECHO) 'Finished building : $@ '
	@$(ECHO) ' '

${OBJDIR}adLunaInit.o : startup/adLunaInit.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$@" -o "$@" "$<"

${OBJDIR}BoardInit_T4MK.o : startup/BoardInit_T4MK.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$@" -o "$@" "$<"

${OBJDIR}startup_adLuna.o : startup/startup_adLuna.s
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) -Wa,$(ASFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$@" -o "$@" "$<"

${OBJDIR}main.o : main.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$@" -o "$@" "$<"

${OBJDIR}Raon_Func.o : Raon_Func.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$@" -o "$@" "$<"

